#lang scribble/manual
 
@title{The Components}

@bold{Software Components}

@margin-note{TODO: Can someone figure out how to indent the component explanations?}

a @italic{scheduler}...

        The XYZ must... 

a @italic{memory allocator}...

    The XYZ must...

a @italic{file system}...

    The XYZ must...

a @italic{shell}...

    The XYZ must...

a @italic{booter}...

    The XYZ must...
